### ISSUE TITLE
Problems reading 123D Step-Files

### ISSUE THREAD

**Issue by andreaswatch** [IxMilia/Step#1]
Hi,
thanks for sharing this project! 
I tried to read a Step-File from AutoDesk 123D and encoured following problems:
- ApplyFileName throws an DateTime -Parsing Exception (-->Just for test I've commented out "//ApplyFileName" in StepReader.cs line 65).
- Lines like this throw the StepReadException "Expected String value"
--> #13=FACE_OUTER_BOUND($,#19,.T.);
change the line to "#13=FACE_OUTER_BOUND('$',#19,.T.);" works fine
- The Items in StepEdgeLoop's containt just Null-Values.

I've attached a sample Step-File: [cube_x20y20z20.zip](https://github.com/IxMilia/Step/files/333611/cube_x20y20z20.zip)

I would try to help, but I'm not sure about your parser/lexer. Do you use a generator for it?

Thanks,
Andreas

**Comment by brettfo** [comment]
Thanks for filing the issue. This project is still very immature so if you're looking for something production-ready then you'd likely have better luck using something else.

That being said, I'm away from a computer for another 10 days or so, so I can't look into the ApplyFileName/DateTime issue.

The 'expected string value' problem is due to the `$` omitted value token which I don't fully support yet.

Off the top of my head I'm not sure why the edge loop contains only null values.

As for the tokenizer and parser, I'm writing that by hand because I like the better error handling i can get.

Once I get back in front of a computer I'll take a look at these problems, and thank you for attaching a file; that'll make fixing these issues much easier.

**Comment by andreaswatch** [comment]
Thanks for reply.
I don't need something production-ready, I work at a leisure project.
For the DateTime Issue I've pushed solution:
https://github.com/IxMilia/Step/compare/master...andreaswatch:master
The DateTime Format of the 123D file differs from yours, so I've changed DateTime.ParseExact to DateTime.Exact -that works for me, but is maybe not what you want to have in your code.
